### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ghost** [mtimjones/7drl#1]
Currently your 7drl is proprietary which means users have no right to do anything with your code (except what's required by GitHub's ToS). If your intent is to let others reuse, learn from, modify or redistribute your code then consider adding a Free Software license to the repo.

**Comment by mtimjones** [comment]
Thanks for letting me know.  I've added a BSD license file allowing anyone to use, modify, redistribute the source.

Thanks,

Tim.
